// HR Letters Service Pack (P2.8)
// Comms is SERVICE. HR is LEADER.
// Responsibilities:
// - Render template
// - Issue doc_no
// - Store in comms_letters (comms own store)
// - Store HTML in DMS (NOTE)
// - Link to HR employee via hr_letter_links + artifacts references

const fs = require('fs');
const path = require('path');

const { nextDocNoAsync } = require('../../../kernel/comms/doc_numbers.service');
const { insertLetter } = require('../repos/comms_letters.repo');
const { insertLink } = require('../../hr/repos/hr_letter_links.repo');
const { storeHtmlAsDocument } = require('./dms_link.adapter');
const { publishPublicArtifact } = require('../../../kernel/artifacts/public_artifacts.service');

function loadPack() {
  const file = path.join(process.cwd(), 'modules', 'comms', 'packs', 'hr_letters', 'templates.json');
  if (!fs.existsSync(file)) {
    return { templates: [] };
  }
  return JSON.parse(fs.readFileSync(file, 'utf8'));
}

function getTemplate(pack, key) {
  return (pack.templates || []).find(t => t.key === key) || null;
}

function renderHtml({ template, data, doc_no, issued_at }) {
  const rows = Object.entries(data || {}).map(([k,v]) =>
    `<tr><td style="border:1px solid #ddd;padding:8px;width:35%"><b>${k}</b></td><td style="border:1px solid #ddd;padding:8px">${String(v)}</td></tr>`
  ).join('');

  return `
  <div dir="rtl" style="font-family:Arial,sans-serif;max-width:820px;margin:0 auto;line-height:1.8">
    <h2>${template.name_ar || template.key}</h2>
    <div style="margin:8px 0;color:#555">رقم الخطاب: <b>${doc_no || '-'}</b> — التاريخ: ${issued_at || '-'}</div>
    <div style="margin:12px 0">${template.body_ar || ''}</div>
    <table style="border-collapse:collapse;width:100%;margin-top:12px">${rows}</table>
    <div style="margin-top:16px;color:#777;font-size:12px">Generated by Ghaith Comms Service (P2.8)</div>
  </div>`;
}

async function previewLetter(ctx, { template_key, data }) {
  const pack = loadPack();
  const template = getTemplate(pack, template_key);
  if (!template) throw Object.assign(new Error('template_not_found'), { code:'template_not_found' });
  return {
    template_key,
    html: renderHtml({ template, data, doc_no: null, issued_at: new Date().toISOString() })
  };
}

async function issueLetter(ctx, { reason, template_key, data, employee_id, related }) {
  const pack = loadPack();
  const template = getTemplate(pack, template_key);
  if (!template) throw Object.assign(new Error('template_not_found'), { code:'template_not_found' });

  const issued_at = new Date().toISOString();
  const doc_no = await nextDocNoAsync({ org_id: ctx.org_id, branch_id: ctx.branch_id, kind: 'letter', prefix: 'HRL' });
  const html = renderHtml({ template, data, doc_no, issued_at });

  // store in comms store
  const letter = await insertLetter({
    org_id: ctx.org_id,
    branch_id: ctx.branch_id,
    doc_no,
    kind: 'hr_letter',
    template_key,
    leader_module: 'hr',
    html,
    qr_data: null,
    meta: { reason, employee_id: employee_id || null, related: related || null }
  });

  // NOTE in DMS
  const file = await storeHtmlAsDocument(ctx, {
    folder_key: 'hr_letters',
    folder_path: `COMMS/HRLetters/${doc_no}`,
    filename: `${doc_no}.html`,
    html,
    meta: { doc_no, template_key, employee_id: employee_id || null, comms_letter_id: letter.id, reason }
  });

  // link to HR employee
  if (employee_id) {
    await insertLink({
      org_id: ctx.org_id,
      branch_id: ctx.branch_id,
      employee_id,
      doc_no,
      comms_letter_id: letter.id,
      dms_file_id: file && file.id ? file.id : null,
      template_key
    });
  }

    // P4.2 optional public publish
  let public_ref = null;
  let public_url = null;
  try{
    if (publish_public && file && file.id) {
      const out = await publishPublicArtifact(ctx, { dms_file_id: file.id, branch_id: ctx.branch_id||null, kind:'comms_hr_letter', title: `HR Letter ${doc_no}`, prefix:'L', ttl_days: public_ttl_days });
      public_ref = out.public_ref;
      public_url = `/public/artifact/${public_ref}`;
    }
  }catch(e){}

  return {
    doc_no,
    issued_at,
    public_ref,
    public_url,
    template_key,
    comms_letter_id: letter.id,
    dms_file_id: file && file.id ? file.id : null,
    html,
    meta: { reason, employee_id: employee_id || null, related: related || null }
  };
}

module.exports = { previewLetter, issueLetter };
