spring:
  application:
    name: ghaith-erp
  logging:
    file:
      name: logs/ghaith-erp.log
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5434}/${DB_NAME:ghaith_erp}
    username: ${DB_USER:ghaith_admin}
    password: ${DB_PASS:ghaith_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME:assaa1122a@gmail.com}
    password: ${SMTP_PASSWORD:tepc lqpl zpiy pkvz}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

server:
  port: 8080

app:
  upload-dir: uploads
  jwt:
    secret: ${APP_JWT_SECRET:VmFsaWRCYXNlNjRTZWNyZXRLZXlGb3JKV1RBdXRoZW50aWNhdGlvbjMyQnl0ZXM=}
    expiration: ${APP_JWT_EXPIRATION:86400000}
